<?php defined('SYSPATH') or die('No direct script access.');

class Controller_Index extends Controller_Template {
	
	// default template
	public $template = 'v_index';

	//убрать дублирование кода (например, title в каждом экшене одинаковый)
	//встроенный метод before
	public function before()
	{
		parent::before(); // TODO: Change the autogenerated stub
		$this->template->title = 'Интернет магазин';
	}


	//http://myshop   default controller and action
	public function action_index()
	{
		$this->template->content = 'Конетент!!!';
	}
	
	//http://myshop/index/catalog index - controller, catalog - action
	public function action_catalog()
	{
		$products = Model::factory('catalog')->all_products();
		//if other template
		$this->template->content = View::factory('v_catalog', array('products' => $products,));
	}

}
